name: DocFX Deployment

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1 

    - name: Build and Deploy DocFX
      run: |
        dotnet tool restore
        dotnet docfx "docfx_project\docfx.json" -q metadata
        
        

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./_site   
