name: DocFX Deployment

on: workflow_dispatch
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v3
    # ...
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json


    - uses: Abaxoth/qwerty@main
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docfx_project/_site
        GH_PAT: ${{ secrets.GH_PAT }}

    
